version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: open5gs-mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      vnet:
        ipv4_address:
          173.22.0.2
          
  open5gs:
    hostname: open5gs
    image: 5g-core
    privileged: true
    build:
       context: .
       dockerfile: Dockerfile.open5gs
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    expose:
      - "38412/sctp"
      - "80/tcp"
    environment:
      - DB_URI=mongodb://mongodb/open5gs
      - WAIT_HOSTS=mongodb:27017
    depends_on:
      - mongodb
    ports: 
      - "38412"    
    command:
      tail -f /dev/null
    networks:
      vnet:
        ipv4_address:
          173.22.0.4
  webui:
    hostname: webui
    image: ${USER}/open5gs-webui
    build:
      context: .
      dockerfile: Dockerfile.webui
    container_name: open5gs-webui
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
      - "9999:9999"
    command:
      tail -f /dev/null
    environment:
      - DB_URI=mongodb://mongodb/open5gs
      - WAIT_HOSTS=mongodb:27017
    networks:
      vnet:
        ipv4_address:
          173.22.0.8  

  enb-ueransim:
    hostname: 5g-enb
    image: 5g-enb
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ueransim
    command:  
      tail -f /dev/null
    networks:
      vnet:
        ipv4_address:
          173.22.0.5

  ue-ueransim:
    hostname: 5g-ue
    image: 5g-ue
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.ueransim
    devices:
      - "/dev/net/tun:/dev/net/tun"
    command:  
      tail -f /dev/null
    networks:
      vnet:
        ipv4_address:
          173.22.0.7
   
volumes:
  mongodb:


networks:
  vnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
      - subnet: 173.22.0.0/24
        gateway: 173.22.0.1
